apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: hcloud
    namespace: kube-system
spec:
    interval: 24h
    url: https://charts.hetzner.cloud
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: hcloud-cloud-controller-manager
    namespace: kube-system
spec:
    releaseName: hcloud-cloud-controller-manager
    chart:
        spec:
            chart: hcloud-cloud-controller-manager
            sourceRef:
                kind: HelmRepository
                name: hcloud
                namespace: kube-system
    interval: 1h0m0s
