apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hcloud
    namespace: kube-system
data:
    token: ENC[AES256_GCM,data:LrNjUhz4C88kQ09VoOX/2SPn9kSYgrKGfp+esdx7MbP5mn6TLD3504td7Bf3IuX+c+OPk7EpTU6CLOKK13+u4NXppo1IviWKIyCYMjllsqXKIXy59QkWZw==,iv:yvZncH67+At6C8jY5eUzotTytyejrphyVnjYOhSWH+0=,tag:M17ZLtvKQMK4web7zBtK5w==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSHdGckNCTVgvV2hUYVhJ
            eHIyazVGdktOMG10MGlrb3lMSk5KS1ZNWkF3CjlMV0RxT1dSQ0czQVFNd1BRaHBt
            NEZrcnBwajZ1bTR3aEVJMHRQNUxtQVkKLS0tIHdEMkJsL0JCVXJ2c05NRFpibktT
            MGllelhvdFNCL1A2R29tdkxhR2ZQazAKwrjIlSL8RgDBaatWFhHA1G/USWXqrbTq
            E3A6SIpcDoEGmjntAcPNuhzEfUtX6mjtwJHlsuybzyK6x+539HpeiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T19:25:31Z"
    mac: ENC[AES256_GCM,data:yIvJV7dmA9YCpwO0gtTIvW4NBP4GCXCmNVf3WbnXGQ1aydy6XCgIjoqvI2OFaEcRr7oGoGFJ/cBEjv57/oO9ZZ7LSWvPDOKMhRY2GoO1xj0I7C/47c4eyEfZxJv2CITtLlC0pZXfzLprwWnVAducvLLmNjn9QspCSSHm/E8ruNQ=,iv:dxU0FHgTMjcMezGxAzm7T+ko+Q0T2yln71GzmMGEXyg=,tag:GLFno+BgHaLS3ZxQUbS9UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: hcloud
    namespace: kube-system
spec:
    interval: 24h
    url: https://charts.hetzner.cloud
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSHdGckNCTVgvV2hUYVhJ
            eHIyazVGdktOMG10MGlrb3lMSk5KS1ZNWkF3CjlMV0RxT1dSQ0czQVFNd1BRaHBt
            NEZrcnBwajZ1bTR3aEVJMHRQNUxtQVkKLS0tIHdEMkJsL0JCVXJ2c05NRFpibktT
            MGllelhvdFNCL1A2R29tdkxhR2ZQazAKwrjIlSL8RgDBaatWFhHA1G/USWXqrbTq
            E3A6SIpcDoEGmjntAcPNuhzEfUtX6mjtwJHlsuybzyK6x+539HpeiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T19:25:31Z"
    mac: ENC[AES256_GCM,data:yIvJV7dmA9YCpwO0gtTIvW4NBP4GCXCmNVf3WbnXGQ1aydy6XCgIjoqvI2OFaEcRr7oGoGFJ/cBEjv57/oO9ZZ7LSWvPDOKMhRY2GoO1xj0I7C/47c4eyEfZxJv2CITtLlC0pZXfzLprwWnVAducvLLmNjn9QspCSSHm/E8ruNQ=,iv:dxU0FHgTMjcMezGxAzm7T+ko+Q0T2yln71GzmMGEXyg=,tag:GLFno+BgHaLS3ZxQUbS9UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: hcloud-cloud-controller-manager
    namespace: kube-system
spec:
    releaseName: hcloud-cloud-controller-manager
    chart:
        spec:
            chart: hcloud-cloud-controller-manager
            sourceRef:
                kind: HelmRepository
                name: hcloud
                namespace: kube-system
    interval: 1h0m0s
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSHdGckNCTVgvV2hUYVhJ
            eHIyazVGdktOMG10MGlrb3lMSk5KS1ZNWkF3CjlMV0RxT1dSQ0czQVFNd1BRaHBt
            NEZrcnBwajZ1bTR3aEVJMHRQNUxtQVkKLS0tIHdEMkJsL0JCVXJ2c05NRFpibktT
            MGllelhvdFNCL1A2R29tdkxhR2ZQazAKwrjIlSL8RgDBaatWFhHA1G/USWXqrbTq
            E3A6SIpcDoEGmjntAcPNuhzEfUtX6mjtwJHlsuybzyK6x+539HpeiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T19:25:31Z"
    mac: ENC[AES256_GCM,data:yIvJV7dmA9YCpwO0gtTIvW4NBP4GCXCmNVf3WbnXGQ1aydy6XCgIjoqvI2OFaEcRr7oGoGFJ/cBEjv57/oO9ZZ7LSWvPDOKMhRY2GoO1xj0I7C/47c4eyEfZxJv2CITtLlC0pZXfzLprwWnVAducvLLmNjn9QspCSSHm/E8ruNQ=,iv:dxU0FHgTMjcMezGxAzm7T+ko+Q0T2yln71GzmMGEXyg=,tag:GLFno+BgHaLS3ZxQUbS9UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
