version: '3'

tasks:
  run:
    cmds:
      - .ci/tilt-with-cluster.sh

  db:shell:
    cmds:
      - turso db shell http://localhost:8080

  db:dump:
    dotenv: ['.env']
    cmds:
      - .ci/db/dump.sh

  db:dump:preview:
    dotenv: ['.env.preview.local']
    cmds:
      - .ci/db/dump.sh

  db:dump:prod:
    dotenv: ['.env.prod.local']
    cmds:
      - .ci/db/dump.sh

  db:restore:
    cmds:
      - .ci/db/drop.sh
      - turso db shell http://localhost:8080 < .ci/db/dump.sql
