version: '3'

tasks:
  run:
    cmds:
      - .ci/tilt-with-cluster.sh

  psql:
    cmds:
      - psql -h localhost -U postgres geometa

  db:dump:
    vars:
      ENVIRONMENT: '{{ .ENV | default `local` }}'
    cmds:
      - |
        if [ "{{.ENVIRONMENT}}" = "local" ]; then
          # local
          psql -h localhost -U postgres postgres -f .ci/db/make-backup.sql >> /dev/null
          echo "Local backup done"
        elif [[ "{{.ENVIRONMENT}}" = "prod" || "{{.ENVIRONMENT}}" = "preview" ]]; then
          # remote
          source .env.{{.ENVIRONMENT}}.local
          pg_dump -d "$DATABASE_URL" -O -x > .ci/db/dump.sql
          echo "drop database if exists geometa with ( force ); create database geometa;" | psql -h localhost -U postgres postgres
          psql -h localhost -U postgres geometa -f .ci/db/dump.sql
        else
          echo "Unknown environment"
        fi
    silent: true

  db:reset:
    cmds:
      - psql -h localhost -U postgres postgres -f .ci/db/reset.sql
