apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
stringData:
    token: ENC[AES256_GCM,data:75pwjUCCVigOdzVFSj6y3kCU+UAugNJEjw1tfERNiDpMiQp1Bi+Iltb87MOxSdTaqCmdELvpLGHYNOvF01v1OUtcXaQ6n681i3Cd/gOloqwrXc9T5bkP2jDugN9q8C+2mJ5wgyWe7o7b+1HYjKZhXdeKJxE1I3sPZVcmz9y9/V5dHmIyibnJ95olCOcQ/rLTseL1nFTsHxUS8UWFVVb1qnhbBVl7pxvZ7WqYQv9bhtdHVOS6Q+VAsw==,iv:5ELOfuEoZz1uVNBBdQv6x84R4YncxCRv3Af0xp7uLfg=,tag:0XNNizwwIntRiLr4VyZnvg==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFZEaGpBakVrNWg2S0FH
            aXdBcmdXaHgzak9EWlRveDdsR0hOZ0YxdVI4CjExUGJYK3pNR2xWQi9jcXpkbWh5
            S3N3c3NGZUxvSnMzYndaUlNuOVRNYXcKLS0tIGNjcTVnc0dFQndwWHdSY0lmYW5l
            amZaY2YwYzB6dGhPdjBiMFNSV1JZQjQKFNftwKhrummgOvn4IYakkcZzJM3nkxck
            9mikHV3gMBtOb5e8Y4IY9H6KPo8tq/HpfV85MY2/TrzFZxAxmbCX0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T21:27:11Z"
    mac: ENC[AES256_GCM,data:1LaZtcJmkgQ/CtmRe8CC0zvJEaxRTvRboibqm95EP5URi3DdHGpnJN08uWrBw7cJguYa8kVoZd2/NI7DFSJWlxAbQ4ud1fh43doIMnqJp9e3c3I9aoVtOY0k1VDgxVGLywxKWwR7z9Sa+YdPxltqiafDylGbCBUkeIAoNPuAj0k=,iv:ev7J8Vg/BVYbgR3PFINdopaqQf1L/ylgRurkvwcIPTg=,tag:lVqxtozWtGznVkuV8CZKlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cloudflared
    name: cloudflared
spec:
    replicas: 3
    selector:
        matchLabels:
            pod: cloudflared
    template:
        metadata:
            creationTimestamp: null
            labels:
                pod: cloudflared
        spec:
            securityContext:
                sysctls:
                    - name: net.ipv4.ping_group_range
                      value: 65532 65532
            containers:
                - command:
                    - cloudflared
                    - tunnel
                    - --no-autoupdate
                    # In a k8s environment, the metrics server needs to listen outside the pod it runs on.
                    # The address 0.0.0.0:2000 allows any pod in the namespace.
                    - --metrics
                    - 0.0.0.0:2000
                    - run
                    - --token-file
                    - /etc/cloudflared-secrets/token
                  image: cloudflare/cloudflared:latest
                  name: cloudflared
                  volumeMounts:
                    - name: cloudflared-secret-volume
                      mountPath: /etc/cloudflared-secrets
                      readOnly: true
                  livenessProbe:
                    httpGet:
                        # Cloudflared has a /ready endpoint which returns 200 if and only if
                        # it has an active connection to the edge.
                        path: /ready
                        port: 2000
                    failureThreshold: 1
                    initialDelaySeconds: 10
                    periodSeconds: 10
            volumes:
                - name: cloudflared-secret-volume
                  secret:
                    secretName: cloudflared
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFZEaGpBakVrNWg2S0FH
            aXdBcmdXaHgzak9EWlRveDdsR0hOZ0YxdVI4CjExUGJYK3pNR2xWQi9jcXpkbWh5
            S3N3c3NGZUxvSnMzYndaUlNuOVRNYXcKLS0tIGNjcTVnc0dFQndwWHdSY0lmYW5l
            amZaY2YwYzB6dGhPdjBiMFNSV1JZQjQKFNftwKhrummgOvn4IYakkcZzJM3nkxck
            9mikHV3gMBtOb5e8Y4IY9H6KPo8tq/HpfV85MY2/TrzFZxAxmbCX0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T21:27:11Z"
    mac: ENC[AES256_GCM,data:1LaZtcJmkgQ/CtmRe8CC0zvJEaxRTvRboibqm95EP5URi3DdHGpnJN08uWrBw7cJguYa8kVoZd2/NI7DFSJWlxAbQ4ud1fh43doIMnqJp9e3c3I9aoVtOY0k1VDgxVGLywxKWwR7z9Sa+YdPxltqiafDylGbCBUkeIAoNPuAj0k=,iv:ev7J8Vg/BVYbgR3PFINdopaqQf1L/ylgRurkvwcIPTg=,tag:lVqxtozWtGznVkuV8CZKlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
