export const plonkitCreditFooter =
  '<p>Description and images taken from: <a href="https://www.plonkit.net/" rel="nofollow" target="_blank">https://www.plonkit.net/</a>.</p>';

export const plonkitFooter =
  '<p>Check out <a href="https://www.plonkit.net/" rel="nofollow" target="_blank">https://www.plonkit.net/</a> for more clues.</p>';

export const countryNames = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Christmas Island',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine State',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const countryContinents: Record<string, string> = {
  'Afghanistan': 'Asia',
  'Albania': 'Europe',
  'Algeria': 'Africa',
  'Andorra': 'Europe',
  'Angola': 'Africa',
  'Argentina': 'South America',
  'Armenia': 'Asia',
  'Australia': 'Oceania',
  'Austria': 'Europe',
  'Azerbaijan': 'Asia',
  'Bahamas': 'North America',
  'Bahrain': 'Asia',
  'Bangladesh': 'Asia',
  'Barbados': 'North America',
  'Belarus': 'Europe',
  'Belgium': 'Europe',
  'Belize': 'North America',
  'Benin': 'Africa',
  'Bhutan': 'Asia',
  'Bolivia': 'South America',
  'Bosnia and Herzegovina': 'Europe',
  'Botswana': 'Africa',
  'Brazil': 'South America',
  'Brunei': 'Asia',
  'Bulgaria': 'Europe',
  'Burkina Faso': 'Africa',
  'Burundi': 'Africa',
  'Cabo Verde': 'Africa',
  'Cambodia': 'Asia',
  'Cameroon': 'Africa',
  'Canada': 'North America',
  'Central African Republic': 'Africa',
  'Chad': 'Africa',
  'Chile': 'South America',
  'China': 'Asia',
  'Colombia': 'South America',
  'Comoros': 'Africa',
  'Congo': 'Africa',
  'Costa Rica': 'North America',
  'Croatia': 'Europe',
  'Cuba': 'North America',
  'Curacao': 'North America',
  'Cyprus': 'Europe',
  'Czechia': 'Europe',
  'Christmas Island': 'Asia',
  'Democratic Republic of the Congo': 'Africa',
  'Denmark': 'Europe',
  'Djibouti': 'Africa',
  'Dominica': 'North America',
  'Dominican Republic': 'North America',
  'Ecuador': 'South America',
  'Egypt': 'Africa',
  'El Salvador': 'North America',
  'Equatorial Guinea': 'Africa',
  'Eritrea': 'Africa',
  'Estonia': 'Europe',
  'Eswatini': 'Africa',
  'Ethiopia': 'Africa',
  'Fiji': 'Oceania',
  'Finland': 'Europe',
  'France': 'Europe',
  'Gabon': 'Africa',
  'Gambia': 'Africa',
  'Georgia': 'Asia',
  'Germany': 'Europe',
  'Ghana': 'Africa',
  'Greece': 'Europe',
  'Grenada': 'North America',
  'Guam': 'Oceania',
  'Guatemala': 'North America',
  'Guinea': 'Africa',
  'Guinea-Bissau': 'Africa',
  'Guyana': 'South America',
  'Haiti': 'North America',
  'Honduras': 'North America',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'India': 'Asia',
  'Indonesia': 'Asia',
  'Iran': 'Asia',
  'Iraq': 'Asia',
  'Ireland': 'Europe',
  'Israel': 'Asia',
  'Italy': 'Europe',
  'Jamaica': 'North America',
  'Japan': 'Asia',
  'Jordan': 'Asia',
  'Kazakhstan': 'Asia',
  'Kenya': 'Africa',
  'Kiribati': 'Oceania',
  'Kuwait': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Laos': 'Asia',
  'Latvia': 'Europe',
  'Lebanon': 'Asia',
  'Lesotho': 'Africa',
  'Liberia': 'Africa',
  'Libya': 'Africa',
  'Liechtenstein': 'Europe',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Madagascar': 'Africa',
  'Malawi': 'Africa',
  'Malaysia': 'Asia',
  'Maldives': 'Asia',
  'Mali': 'Africa',
  'Malta': 'Europe',
  'Marshall Islands': 'Oceania',
  'Mauritania': 'Africa',
  'Mauritius': 'Africa',
  'Mexico': 'North America',
  'Micronesia': 'Oceania',
  'Moldova': 'Europe',
  'Monaco': 'Europe',
  'Mongolia': 'Asia',
  'Montenegro': 'Europe',
  'Morocco': 'Africa',
  'Mozambique': 'Africa',
  'Myanmar': 'Asia',
  'Namibia': 'Africa',
  'Nauru': 'Oceania',
  'Nepal': 'Asia',
  'Netherlands': 'Europe',
  'New Zealand': 'Oceania',
  'Nicaragua': 'North America',
  'Niger': 'Africa',
  'Nigeria': 'Africa',
  'North Korea': 'Asia',
  'North Macedonia': 'Europe',
  'Northern Mariana Islands': 'Oceania',
  'Norway': 'Europe',
  'Oman': 'Asia',
  'Pakistan': 'Asia',
  'Palau': 'Oceania',
  'Palestine State': 'Asia',
  'Panama': 'North America',
  'Papua New Guinea': 'Oceania',
  'Paraguay': 'South America',
  'Peru': 'South America',
  'Philippines': 'Asia',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Puerto Rico': 'North America',
  'Qatar': 'Asia',
  'Romania': 'Europe',
  'Russia': 'Asia',
  'Rwanda': 'Africa',
  'Saint Kitts and Nevis': 'North America',
  'Saint Lucia': 'North America',
  'Saint Vincent and the Grenadines': 'North America',
  'Samoa': 'Oceania',
  'San Marino': 'Europe',
  'Sao Tome and Principe': 'Africa',
  'Saudi Arabia': 'Asia',
  'Senegal': 'Africa',
  'Serbia': 'Europe',
  'Seychelles': 'Africa',
  'Sierra Leone': 'Africa',
  'Singapore': 'Asia',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Solomon Islands': 'Oceania',
  'Somalia': 'Africa',
  'South Africa': 'Africa',
  'South Korea': 'Asia',
  'South Sudan': 'Africa',
  'Spain': 'Europe',
  'Sri Lanka': 'Asia',
  'Sudan': 'Africa',
  'Suriname': 'South America',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Syria': 'Asia',
  'Taiwan': 'Asia',
  'Tajikistan': 'Asia',
  'Tanzania': 'Africa',
  'Thailand': 'Asia',
  'Timor-Leste': 'Oceania',
  'Togo': 'Africa',
  'Tonga': 'Oceania',
  'Trinidad and Tobago': 'North America',
  'Tunisia': 'Africa',
  'Turkey': 'Asia',
  'Turkmenistan': 'Asia',
  'Tuvalu': 'Oceania',
  'Uganda': 'Africa',
  'Ukraine': 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'United States of America': 'North America',
  'United States': 'North America',
  'Uruguay': 'South America',
  'Uzbekistan': 'Asia',
  'Vanuatu': 'Oceania',
  'Vatican City': 'Europe',
  'Venezuela': 'South America',
  'Vietnam': 'Asia',
  'Yemen': 'Asia',
  'Zambia': 'Africa',
  'Zimbabwe': 'Africa',
};
