apiVersion: apps/v1
kind: Deployment
metadata:
  name: libsql-server
spec:
  selector:
    matchLabels:
      app: libsql-server
  template:
    metadata:
      labels:
        app: libsql-server
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: libsql-server
          image: ghcr.io/tursodatabase/libsql-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/lib/libsql/data
              name: libsql-data-disk
      volumes:
        - name: libsql-data-disk
          hostPath:
            path: /data/libsql
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: libsql-svc
spec:
  selector:
    app: libsql-server
  ports:
    - port: 8080
