apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: kube-system
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: kube-system
spec:
  releaseName: redis-operator
  chart:
    spec:
      chart: redis-operator
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: kube-system
  interval: 1h0m0s
