apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  defaultBackend:
    service:
      name: api
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - geometa-prod-api
