apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-allow-token-review
subjects:
  - kind: ServiceAccount
    name: api
roleRef:
  kind: ClusterRole
  name: token-reviewer
  apiGroup: rbac.authorization.k8s.io
