apiVersion: v1
kind: Namespace
metadata:
  name: geometa-prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: geometa-prod
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: geometa-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
