apiVersion: v1
kind: Namespace
metadata:
  name: geometa-prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: geometa-prod-frontend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/frontend/flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: geometa-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: geometa-prod-api
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/api/flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: geometa-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
