apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: docker.io/registry:3
          resources:
            limits:
              memory: "600Mi"
              cpu: "2"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: auth-volume
              mountPath: /auth/htpasswd
              subPath: htpasswd
              readOnly: true
          env:
            # auth
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            # s3
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: AWS_ACCESS_KEY_ID
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: AWS_SECRET_ACCESS_KEY
            - name: REGISTRY_STORAGE_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: REGISTRY_STORAGE_S3_REGION
            - name: REGISTRY_STORAGE_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: REGISTRY_STORAGE_S3_BUCKET
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: REGISTRY_STORAGE_S3_REGIONENDPOINT
            - name: REGISTRY_STORAGE_S3_FORCEPATHSTYLE
              value: "true"
            - name: REGISTRY_STORAGE_S3_SECURE
              value: "true"

      volumes:
        - name: auth-volume
          secret:
            secretName: registry
            items:
              - key: htpasswd
                path: htpasswd
