apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - geometa-prod-web
