apiVersion: v1
kind: Secret
metadata:
    name: web
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0pM5FAviCqNMpV/tdFdHuyemvAGNV5vRuJNtgolLGKU=,iv:QcDzPBP8diuLY+HMCRHW4Q5kGME14CubCjSnx/nnz0E=,tag:wI8bbsmFgxiDVXUu4xKKtg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:erqm19/PDlyQ0ARb5bOe1JQxZiR3OZhEj7+M3c7ShPRcrXPePZDqBTO5bl9sBVvjtcKr2OWIC0yxQL7RjneXkg==,iv:IDDKUhJatAMGOfe4rOnmcQAkNg4fpCwfSHP8Fgzb1r0=,tag:G90Xh3ohollW/pq9gvi83w==,type:str]
    CLOUDFLARE_BEARER: ENC[AES256_GCM,data:3HOcdW/Ct9uqyE7z2oDwHox6cCc5kDWNenLls+0i9Xdq31PJQk5SEQ==,iv:OSUndql6oG7jacugm+wlK5HEQAm/ujIA1SjRpFEeZLI=,tag:dkHKDSM8uKaTLsRJB64+Jw==,type:str]
    CLOUDFLARE_KV_NAMESPACE_ID: ENC[AES256_GCM,data:bxB3pvc2KQMxx5ynu8ieoYvUPqSdIwAfz+ajylr4MGI=,iv:4+CjTJ1ES3d4w+plpaR97hzuO1RvPOwjDNI6D71k9OY=,tag:9qn06IA8b9VxAKifj5p5hw==,type:str]
    CRONJOBS_API_TOKEN: ENC[AES256_GCM,data:vdYPNMU/+L5tzYdALZhZ5S++A/9sy53Y,iv:QKMLpbGNc8f/QSDvncUDX3wvr23uNlpSfoOSgNZU7hI=,tag:mmfiSPSjhsgz81odaxyS9g==,type:str]
    DISCORD_SECRET_ID: ENC[AES256_GCM,data:ZFzOk56Ab7Hep/aMiz6e7saVIZumihw8n7rYhE7hm9A=,iv:yHy/AGMkyeAZvTJ8vcsJVEcFZkGz+uip7l3xdTlCX7A=,tag:JUFA3BzeptshF5erm1JPXQ==,type:str]
    SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:pEjiVj3tEqSgQ/UzpEbPdchUfk+o5uCIT8D7K0vF8Y44kc/t+Bm7pe9OUQEazsyUZrSFZVLq6IL6SEKX8HWCItuPtSc5uqf0Of9R+46I4zDPyDNwhg+I7C3xTfXnoOcN2pVr4vFeU5474faKU7ZJ4+B0IzX5/5o5cj5p9pMn4zn5V5puGLwhoS3Us0mVthRMXmqss2oV4TBx0u7aij5xKs6nlNUghtbKhjas4/Bw16l7d2hEXPa63JaRczjiaII=,iv:teE72VImAiNYUTW9tE4nx0df9vyrUGSQQwjUW8AqWOY=,tag:K37uZnUWnGRajPUoKNn4eA==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T16:45:52Z"
    mac: ENC[AES256_GCM,data:nD/8VMLvN4+379gTjKud0YvM+1rJbBVgxpLcjMVvDIl8OHvH8JSOoAm+gYjmR8hXW5emz5P0/vP7J5Y0FOa+LqJ+D9XMH8fZYTkZYeCS2QYmvz861KfQAUu/G1thyE5SjFQZvU1F1iLUEU54eU+Fp3Y53wuXkOHiS6xLIJUR1mc=,iv:UmxRelvpRllHQ28XXyKZ7qKysqJA6tJvIZ00VkMxUOM=,tag:jTl6yUwmXgMetNtLRQ+uaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
