apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
spec:
  image: ghcr.io/likeon/geometa-frontend
  interval: 5m
  provider: generic
  secretRef:
    name: registries
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
spec:
  imageRepositoryRef:
    name: frontend
  filterTags:
    pattern: '^k8s-.+?-(?P<ts>[\d]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: frontend
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'frontend: automated image update'
    push:
      branch: k8s
  update:
    path: ./apps/frontend/flux
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: frontend-update-receiver
spec:
  type: generic
  secretRef:
    name: frontend-update-webhook-token
  events: ["workflow_dispatch"]
  resources:
    - apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImageRepository
      name: frontend
