apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PU0Qe0ydS0ZuyMXpRylYdJ21/Jg=,iv:m7g8EJiyX0V0UQ+rdykLvHzbmRbg72OmTEkdA3gib4Q=,tag:Bz4LqwWtvVEkk33nS6KLFg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+o6IQ0AFdRKp7ZSZay+rOkpS6MSQOqSSKBcYMHkHbOZJwFO3st5Byw==,iv:aksEECIANxE13qqx5xoKo68XaAcQBt5R/R2dRyVsQTE=,tag:WDsrChQBWHhMzrfcnSBrTQ==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVWZmVEdzMFVPb1dqNjN4
            dU9hWFd0S3ptREdNUzA3dmd0a1lFMHN3KzNJClg4aGFZVzFQb0c2WHg3VnEwcWoz
            QzdaNmlXbzhubnZLc2xiL3k2KytYMWcKLS0tIE13T3hIaHJYN3RqblFCWGs5MHh6
            L2NwQmJVSTkyV3l0MCtsS0psTDJVQ0EKDEfOCDkdG8dPHXoSYinYf9wtxp9MGTXO
            Qp2SbLlfOTU6rRIMsqhafy8x7nLzVeRYq5Qv4B/D3BJBZ73hpvb9jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T22:06:26Z"
    mac: ENC[AES256_GCM,data:LugoeNYPD4JU8X80Z3zW4X3KjQEkrTxC81DTLCSynhBbLKn8mtYHn/jlqHsvJgHzJr3Zc7hPJ/CTaH7TKhFTmvPn99H6SZ6VxUfbmyJIUCdASkpJUKJ60IF+VJjGCeaSZZxd9MgfporOlhKsdyqkKLttU5L/1JVoLrrNMAyP9LY=,iv:+vV+wERkqkQy9dDhpU84YP1RfoqIOdndBkkcRT3nk2U=,tag:AXSwwP4Md+CLVbj3F7Cg4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
